package dev.sonora.backend

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.File
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.json.Json

/** A login the user asked to be remembered. */
@Serializable
data class SavedCredentials(val username: String, val password: String)

/**
 * The envelope a stored login is written in: the initialisation vector and the ciphertext, base64,
 * separated by a colon.
 *
 * Its own object so it can be tested on a machine. The crypto around it cannot be — the Android
 * Keystore only exists on a device — and a format that silently fails to parse would look exactly
 * like a forgotten login.
 */
internal object CredentialEnvelope {

    fun encode(iv: ByteArray, body: ByteArray): String {
        val encoder = Base64.getEncoder()
        return "${encoder.encodeToString(iv)}:${encoder.encodeToString(body)}"
    }

    fun decode(text: String): Pair<ByteArray, ByteArray>? {
        // Exactly two parts, and base64 never contains a colon, so anything else is not one of ours.
        val parts = text.split(':')
        if (parts.size != 2) return null

        return runCatching {
            val decoder = Base64.getDecoder()
            decoder.decode(parts[0]) to decoder.decode(parts[1])
        }.getOrNull()
    }
}

/**
 * The login, kept encrypted under a key that cannot leave the device.
 *
 * A password has to be stored to be worth storing, so the question is only how badly it can go
 * wrong. The file sits in app-private storage like every other document the app keeps, and on top
 * of that it is encrypted with an AES key generated inside the Android Keystore: the key can be used
 * but never read back out, so a copy of the file — a backup, a rooted device — is not a copy of the
 * password.
 *
 * Every read is best-effort. A file that cannot be decrypted, because the key is gone or the file
 * was restored from another device, is treated as no login at all rather than as an error: the user
 * signs in again, which is the outcome they would have chosen anyway.
 */
class CredentialStore(private val context: Context) {

    private val json = Json { ignoreUnknownKeys = true }

    private val file = File(context.filesDir, CREDENTIALS_FILE)

    private val document by lazy { JsonFile(file, String.serializer()) }

    fun load(): SavedCredentials? {
        val envelope = document.read() ?: return null
        val (iv, body) = CredentialEnvelope.decode(envelope) ?: return null

        return runCatching {
            json.decodeFromString<SavedCredentials>(decrypt(iv, body))
        }.getOrNull()
    }

    fun save(credentials: SavedCredentials) {
        val (iv, body) = encrypt(json.encodeToString(credentials))
        document.write(CredentialEnvelope.encode(iv, body))
    }

    /**
     * Forgets it, key and all.
     *
     * Deleting the key is the part that matters: without it what was written is not merely hidden
     * but unreadable, including from a copy taken beforehand.
     */
    fun clear() {
        file.delete()
        runCatching { keyStore().deleteEntry(ALIAS) }
    }

    private fun encrypt(plain: String): Pair<ByteArray, ByteArray> {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())

        // The IV is generated by the cipher and has to be kept: without it the body cannot be read.
        return cipher.iv to cipher.doFinal(plain.toByteArray())
    }

    private fun decrypt(iv: ByteArray, body: ByteArray): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(TAG_BITS, iv))

        return cipher.doFinal(body).decodeToString()
    }

    private fun secretKey(): SecretKey {
        val store = keyStore()
        (store.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .build(),
        )

        return generator.generateKey()
    }

    private fun keyStore(): KeyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val ALIAS = "sonora.credentials"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val TAG_BITS = 128
        const val CREDENTIALS_FILE = "credentials.json"
    }
}
